
name: OPERA disp s1 hist status ops

on:
  schedule:
    # Runs around midnight Pacific Time (UTC-7)
    # Doesn't account for daylight saving transitions
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  opera-disp-s1-hist-status-ops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Retrieve disp s1 hist status html
        run: |
          cd monitoring
          python opera_disp_s1_status_html.py

      # reference: https://github.com/stefanzweifel/git-auto-commit-action
      - name: Commit and Push to Github
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            file_pattern: 'monitoring/*.html'
            commit_user_name: 'opera_sds'
            commit_user_email: 'opera-sds@jpl.nasa.gov'
            commit_author: OPERA SDS <opera-sds@jpl.nasa.gov>
          
    
