
name: OPERA Daily Products Query

on:
  schedule:
    # Runs around midnight Pacific Time (UTC-7)
    # Doesn't account for daylight saving transitions
    - cron: "0 */4 * * *"
  # Runs on pushes targeting the default branch
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  opera-daily-products-query:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute Daily Products Query
        run: |
          cd monitoring
          python opera_daily_products_query.py
      - name: Save Report Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: 'monitoring/archive_data'
          retention-days: 30
      - name: Clean Individual Artifacts
        run: rm -rf monitoring/archive_data
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
