
name: OPERA Daily Latency Query

on:
  schedule:
    # Runs around 5pm Pacific Time (UTC-7) everyday
    # Doesn't account for daylight saving transitions
    - cron: "0 17 */1 * *"
  workflow_dispatch:

jobs:
  opera-daily-products-query:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Daily Product Latency
        run: |
          cd monitoring
          python latency_graph.py

      # reference: https://github.com/stefanzweifel/git-auto-commit-action
      - name: Commit and Push to Github
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            file_pattern: 'monitoring/opera_latency_query.png'
            commit_user_name: 'opera_sds'
            commit_user_email: 'opera-sds@jpl.nasa.gov'
            commit_author: OPERA SDS <opera-sds@jpl.nasa.gov>
          
    
